#zf220207.1804
# sources: https://garagehq.deuxfleurs.fr/documentation/cookbook/real-world/

version: "3.9"

#docker run \
#  -d \
#  --name garaged \
#  --restart always \
#  --network host \
#  -v /etc/garage.toml:/etc/garage.toml \
#  -v /var/lib/garage/meta:/var/lib/garage/meta \
#  -v /var/lib/garage/data:/var/lib/garage/data \
#  lxpz/garage_amd64:v0.4.0


services:
  garage:
    container_name: garaged
    restart: unless-stopped
    image: dxflrs/amd64_garage:v0.6.0
    ports:
      - '3900:3900'
      - '3901:3901'
      - '3902:3902'
    volumes:
      - $PWD/garage.toml:/etc/garage.toml
      - $PWD/meta:/var/lib/garage/meta
      - $PWD/data:/var/lib/garage/data


